[project]
authors = ["Bia Villas Boas <villasboas@mines.edu>", "Gwendal Marechal <gwendal.marechal@utoulouse.fr>"]
channels = ["conda-forge"]
name = "swot"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
numpy = ">=2.3.0,<3"
matplotlib = ">=3.10.3,<4"
jupyter = ">=1.1.1,<2"
ipython = ">=9.3.0,<10"
netcdf4 = ">=1.7.2,<2"
xarray = ">=2025.6.1,<2026"
cartopy = ">=0.24.0,<0.25"
cmocean = ">=4.0.3,<5"
ruff = ">=0.12.8,<0.13"
pandas = ">=2.3.1,<3"

